openapi: 3.0.1
info:
  version: 1.0.0
  title: My Finance Pal
  description: API of the personal finance budgeting app My Finance Pal
tags:
  - name: expenses
    description: Expenses of budgets
  - name: budgets
    description: Managing budgets
paths:
  /budgets:
    # TODO 1. add a new endpoint for creating budgets
    post:
      tags:
        - budgets
      description: Create a new budget
      operationId: createBudget
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBudget'
      responses:
        201:
          description: Budget created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
    get:
      tags:
        - budgets
      description: Get all budgets
      operationId: getBudgets
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Budget"
  /budgets/{budgetId}/summary:
    get:
      tags:
        - budgets
      description: Get a budget summary including all expenses for a given ID
      operationId: getBudgetSummary
      parameters:
        - in: path
          name: budgetId
          required: true
          description: The UUID of the budget
          schema:
            $ref: "#/components/schemas/BudgetId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BudgetSummary"
        404:
          description: Budget not found
  /budgets/{budgetId}:
    delete:
      tags:
        - budgets
      description: Delete a budget including all expenses
      operationId: deleteBudget
      parameters:
        - in: path
          name: budgetId
          required: true
          description: The UUID of the budget
          schema:
            $ref: "#/components/schemas/BudgetId"
      responses:
        204:
          description: Budget successfully deleted
        404:
          description: Budget not found
  /budgets/{budgetId}/expenses:
    post:
      tags:
        - expenses
      description: Register a new expense for a budget
      operationId: createExpense
      parameters:
        - $ref: "#/components/parameters/BudgetIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewExpense"
      responses:
        201:
          description: Expense created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
        404:
          description: Budget not found

components:
  parameters:
    BudgetIdParam:
      in: path
      name: budgetId
      required: true
      description: The UUID of the budget
      schema:
        $ref: "#/components/schemas/BudgetId"
    ExpenseIdParam:
      in: path
      name: expenseId
      required: true
      description: The UUID of the expense
      schema:
        $ref: "#/components/schemas/ExpenseId"
  schemas:
    BudgetId:
      type: string
      format: uuid
      description: Unique identifier of one budget
      example: 850963b9-a04d-4698-b767-c0a0096b37c5
    Budget:
      allOf:
        - type: object
          description: Planned money to be available for tracking expenses related to a certain purpose over a period of time
          required:
            - id
            - spent
          properties:
            id:
              $ref: "#/components/schemas/BudgetId"
            spent:
              type: number
              minimum: 0
              description: The summed up spent amount of all expenses of that budget
        - $ref: "#/components/schemas/NewBudget"
    BudgetSummary:
      allOf:
        - $ref: "#/components/schemas/Budget"
        - type: object
          description: Summary of the whole budget including all expenses
          required:
            - expenses
          properties:
            expenses:
              type: array
              description: All expenses of the budget
              items:
                $ref: "#/components/schemas/Expense"
    NewBudget:
      type: object
      description: Budget to be created
      required:
        - name
        - limit
      properties:
        name:
          type: string
          description: The name of the budget
          example: Takeout
        limit:
          type: number
          minimum: 0
          description: The total amount available for the budget
          example: 250
        startDate:
          type: string
          format: date
          description: Date marking the start of the budget period
          example: 2023-04-01
        endDate:
          type: string
          format: date
          description: Date marking the end of the budget period
          example: 2023-04-30
    ExpenseId:
      type: string
      format: uuid
      description: Unique identifier of a expense
      example: cfd3b0b7-bf5e-43d4-8341-940d5e07487d
    Expense:
      allOf:
        - $ref: "#/components/schemas/NewExpense"
        - type: object
          description: An expense related to a single budget
          required:
            - id
          properties:
            id:
              $ref: "#/components/schemas/ExpenseId"
    NewExpense:
      type: object
      description: A new expense to be created
      required:
        - description
        - amount
        - date
      properties:
        description:
          type: string
          description: Description of the expense
          example: Healthy breakfast at Five Guys
        amount:
          type: number
          description: Amount of money contained in the expense
          minimum: 0
          example: 23.94
        date:
          type: string
          format: date-time
